name: Run Parser

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run parser
        run: python parser.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update data" || echo "No changes"
          git push
